# Generated by Django 5.2.5 on 2025-08-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address_line1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address_line2',
        ),
    ]
